CaraLuggage/Models/UserProfile.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CaraLuggage.Models
{
    public class UserProfile
    {
        public string Name { get; set; }
        public string Email { get; set; }
    }
}

CaraLuggage/Controllers/LoginRegisterController.cs
using CaraLuggage.Controllers.ProxyPattern;
using CaraLuggage.Models;
using Facebook;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Security.Cryptography.Pkcs;
using System.Web;
using System.Web.Mvc;
using GoogleAuthentication.Services;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Diagnostics;
using CaraLuggage.Controllers.Singleton;
using System.Web.Helpers;
using System.Xml.Linq;

namespace QuanLyShopBanVali.Controllers
{
    public class LoginRegisterController : Controller
    {
        private CaraLuggageDBEntities db = new CaraLuggageDBEntities();

        // GET: LoginRegister
        public ActionResult LoginSection()
        {
            var socialService = SocialAuthService.Instance;

            ViewBag.Url = socialService.GetFacebookLoginUrl("https://localhost:44357/FacebookRedirect");

            ViewBag.repsone = socialService.GetGoogleAuthUrl("https://localhost:44357/dang-nhap-google");

            return View();
        }


        public ActionResult RegisterSection()
        {
            return View();
        }

        //Lấy các thông tin Facebook
        public async Task<ActionResult> FacebookRedirect(string code, TaiKhoan taiKhoan, KhachHang khachHang)
        {
            var socialService = SocialAuthService.Instance;

            var result = await socialService.GetFacebookLoginDetails(code, "https://localhost:44357/FacebookRedirect");
            string name = result.name;
            string email = result.email;

            string newCustomerID;

            do
            {
                newCustomerID = GenerateRandomCustomerID();
            }

            while (db.KhachHangs.Any(p => p.customer_id == newCustomerID));

            taiKhoan.account_name = email;

            KhachHang checkCus = db.KhachHangs.FirstOrDefault(c => c.customer_account == email);

            if (checkCus != null)
            {
                KhachHang existedCus = db.KhachHangs.FirstOrDefault(k => k.customer_id == checkCus.customer_id);

                if (existedCus == null)
                {
                    khachHang.customer_id = newCustomerID;

                    khachHang.customer_name = name;

                    khachHang.customer_account = email;

                    db.KhachHangs.Add(khachHang);
                    db.TaiKhoans.Add(taiKhoan);
                    db.SaveChanges();
                    Session["CusID"] = khachHang.customer_id;
                }

                Session["CusID"] = existedCus.customer_id;
                Session["isCustomer"] = "isCustomer";
                Session["Username"] = email;
                Session["LoginFB_GG"] = true;
            }

            else
            {
                khachHang.customer_id = newCustomerID;

                khachHang.customer_name = name;

                khachHang.customer_account = email;

                db.KhachHangs.Add(khachHang);
                db.TaiKhoans.Add(taiKhoan);
                db.SaveChanges();
                Session["CusID"] = khachHang.customer_id;
                Session["isCustomer"] = "isCustomer";
                Session["Username"] = email;
                Session["LoginFB_GG"] = true;
            }

            // Chuyển hướng đến trang chính
            return RedirectToAction("Index", "Home");
        }


        //Lấy các thông tin từ Google
        public async Task<ActionResult> GoogleLoginCallBack(string code, TaiKhoan taiKhoan, KhachHang khachHang)
        {
            var socialService = SocialAuthService.Instance;

            var result = await socialService.GetUserProfileFromGoogle(code);

            string name = result.Name;
            string email = result.Email;

            string newCustomerID;

            do
            {
                newCustomerID = GenerateRandomCustomerID();
            }

            while (db.KhachHangs.Any(p => p.customer_id == newCustomerID));
            taiKhoan.account_name = email;

            KhachHang checkCus = db.KhachHangs.FirstOrDefault(c => c.customer_account == email);

            if (checkCus != null)
            {
                KhachHang existedCus = db.KhachHangs.FirstOrDefault(k => k.customer_id == checkCus.customer_id);

                if (existedCus == null)
                {
                    khachHang.customer_id = newCustomerID;
                    khachHang.customer_name = name;

                    khachHang.customer_account = email;

                    db.KhachHangs.Add(khachHang);
                    db.TaiKhoans.Add(taiKhoan);
                    db.SaveChanges();
                    Session["CusID"] = khachHang.customer_id;
                }

                Session["CusID"] = existedCus.customer_id;
                Session["isCustomer"] = "isCustomer";
                Session["Username"] = email;
                Session["LoginFB_GG"] = true;
            }

            else
            {
                khachHang.customer_id = newCustomerID;
                khachHang.customer_name = name;

                khachHang.customer_account = email;

                db.KhachHangs.Add(khachHang);
                db.TaiKhoans.Add(taiKhoan);
                db.SaveChanges();
                Session["CusID"] = khachHang.customer_id;
                Session["isCustomer"] = "isCustomer";
                Session["Username"] = email;
                Session["LoginFB_GG"] = true;
            }

            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult LoginSection(LoginInfo loginInfo)
        {
            ILogin loginProxy = new LoginProxy();

            if (loginProxy.ValidateLogin(loginInfo))
            {
                if (loginProxy.CheckUserRole(loginInfo))
                {
                    // Set the "UserCode" session variable to the user code
                    Session["UserName"] = loginInfo.UserName;

                    KhachHang khachHang = db.KhachHangs.FirstOrDefault(c => c.customer_account == loginInfo.UserName);

                    Session["CusID"] = khachHang.customer_id;

                    Session["isCustomer"] = "isCustomer";

                    return RedirectToAction("Index", "Home");
                }
                else if (!loginProxy.CheckUserRole(loginInfo))
                {
                    Session["UserName"] = loginInfo.UserName;

                    return RedirectToAction("Index", "AdminDashboard");
                }
                else
                {
                    // Invalid login, return to the login page with an error message
                    ModelState.AddModelError("", "Invalid account name or password");

                    // Return the loginInfo object to repopulate the form with user-entered values
                    return View("LoginSection", loginInfo);
                }
            }
            else
            {
                // Invalid login, return to the login page with an error message
                ModelState.AddModelError("", "Account has been banned!!!");

                // Return the loginInfo object to repopulate the form with user-entered values
                return RedirectToAction("LoginSection", loginInfo);
            }
        }


        public static string GenerateRandomCustomerID()
        {
            // Tạo một đối tượng Random
            Random random = new Random();

            // Tạo một mảng chứa các ký tự chữ cái và số
            char[] chars = new char[] {
                'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',
                'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't',
                'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D',
                'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N',
                'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X',
                'Y', 'Z', '0', '1', '2', '3', '4', '5', '6', '7',
                '8', '9'
            };


            // Tạo một chuỗi rỗng
            string code = "";

            // Lặp lại cho đến khi chuỗi có độ dài mong muốn
            for (int i = 0; i < 10; i++)
            {
                // Chọn ngẫu nhiên một ký tự từ mảng
                int index = random.Next(chars.Length);
                char c = chars[index];

                // Thêm ký tự vào chuỗi
                code += c;
            }

            return code;
        }

        // POST: KhachHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RegisterSection([Bind(Include = "customer_id,customer_name,customer_phone,customer_address,customer_account")] KhachHang khachHang, 
            [Bind(Include = "account_name,account_password,account_createAt,account_status")] TaiKhoan taiKhoan)
        {
            string newCustomerID;

            do
            {
                newCustomerID = GenerateRandomCustomerID();
            }
            while (db.KhachHangs.Any(p => p.customer_id == newCustomerID));

            khachHang.customer_id = newCustomerID;

            if (ModelState.IsValid)
            {
                taiKhoan.account_createAt = DateTime.Now;
                taiKhoan.account_status = true;

                db.TaiKhoans.Add(taiKhoan);
                db.SaveChanges();

                khachHang.customer_account = taiKhoan.account_name;
                db.KhachHangs.Add(khachHang);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("Index", "Home", khachHang);
        }

        public ActionResult Logout()
        {
            // Clear session
            Session.Clear();

            // Redirect to the login page

CaraLuggage/Controllers/ProductDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CaraLuggage.Models;

namespace QuanLyShopBanVali.Controllers
{
    public class ProductDetailController : Controller
    {
        private CaraLuggageDBEntities db = new CaraLuggageDBEntities();

        // GET: ProductDetail
        public ActionResult Index(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham product = db.SanPhams.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }

            var brands = db.ThuongHieux.ToList();

            // Tạo một Dictionary để lưu trữ brand_name tương ứng với mỗi brand_id
            Dictionary<int, string> brandNames = new Dictionary<int, string>();

            // Duyệt qua danh sách thương hiệu và thêm vào Dictionary
            foreach (var brand in brands)
            {
                brandNames.Add(brand.brand_id, brand.brand_name);
            }

            ViewBag.BrandNames = brandNames;

            // Lấy danh sách sản phẩm
            var relatedProduct = db.SanPhams.Where(p => p.product_brand == product.product_brand || p.product_category == product.product_category).Take(4).ToList();

            ViewBag.relatedProduct = relatedProduct;

            var productCates = db.SanPhams.Where(p => p.product_category == product.product_category).ToList();

            ViewBag.sameCate = productCates;

            return View(product);
        }
    }
}

CaraLuggage/Views/Home/About.cshtml
@{
    ViewBag.Title = "Về chúng tôi";
    Layout = "~/Views/Shared/UserView.cshtml";
}
<section id="page-header" class="about-header">
    <h2>#HieuChungToi</h2>
</section>

<section id="about-head" class="section-p1">
    <img src="~/Content/assets/img/about/a6.jpg" alt="">
    <div>
        <h2>Chúng tôi là ai?</h2>
        <p>Chúng tôi là <span style="color: #0cc5b9">Cara Luggage Store</span> </p>
        <p>Là một doanh nghiệp chuyên cung cấp các loại vali, balo, túi xách,... thời thượng và chất lượng cao dành cho mọi hoạt động đời sống.</p>
        @*<abbr title="">Create stunning images with as much or little control as you like thanks to a choice of Basic and Create modes</abbr>*@
        <br>
        <br>
        @*<marquee bgcolor="#ccc" loop="-1" scrollamount="5" width="100%">Create stunning images with as much or little control as you like thanks to a choice of Basic and Create modes</marquee>*@
    </div>
</section>

@*<section id="about-app" class="section-p1">
    <h1>Download Our <a href="#">App</a></h1>
    <div class="video">
        <video autoplay muted loop src="~/Content/assets/img/about/1.mp4"></video>
    </div>
</section>*@

<section class="section-p1" id="feature">
    <div class="fe-box">
        <img src="~/Content/assets/img/features/f1.png" alt="">
        <h6>Free Shipping</h6>
    </div>
    <div class="fe-box">
        <img src="~/Content/assets/img/features/f2.png" alt="">
        <h6>Online Order</h6>
    </div>
    <div class="fe-box">
        <img src="~/Content/assets/img/features/f3.png" alt="">
        <h6>Save Money</h6>
    </div>
    <div class="fe-box">
        <img src="~/Content/assets/img/features/f4.png" alt="">
        <h6>Promotions</h6>
    </div>
    <div class="fe-box">
        <img src="~/Content/assets/img/features/f5.png" alt="">
        <h6>Happy Sell</h6>
    </div>
    <div class="fe-box">
        <img src="~/Content/assets/img/features/f6.png" alt="">
        <h6>F24/7 Support</h6>
    </div>
</section>

CaraLuggage/Views/Home/Index.cshtml
@model IEnumerable<CaraLuggage.Models.SanPham>

@{
    ViewBag.Title = "Trang chủ";
    Layout = "~/Views/Shared/UserView.cshtml";
}
@using CaraLuggage.Controllers.DecoratorPattern;


<section id="hero" class="dark-mode">
    <h4>Ưu đãi</h4>
    <h2>Nhiều Ưu Đãi Siêu Giá Trị</h2>
    <h1>Trên Tất Cả Sản Phẩm</h1>
    <p>Giảm giá lên đến 70%</p>
    <button>Mua Ngay</button>
</section>

<section class="dark-mode section-p1" id="feature">
    <div class="fe-box">
        <img src="~/Content/assets/img/features/f1.png" alt="">
        <h6>Free Shipping</h6>
    </div>
    <div class="fe-box">
        <img src="~/Content/assets/img/features/f2.png" alt="">
        <h6>Online Order</h6>
    </div>
    <div class="fe-box">
        <img src="~/Content/assets/img/features/f3.png" alt="">
        <h6>Save Money</h6>
    </div>
    <div class="fe-box">
        <img src="~/Content/assets/img/features/f4.png" alt="">
        <h6>Promotions</h6>
    </div>
    <div class="fe-box">
        <img src="~/Content/assets/img/features/f5.png" alt="">
        <h6>Happy Sell</h6>
    </div>
    <div class="fe-box">
        <img src="~/Content/assets/img/features/f6.png" alt="">
        <h6>F24/7 Support</h6>
    </div>
</section>

<!-- ... (các phần code khác) ... -->

<section class="dark-mode section-p1" id="products1">
    <h2>Sản phẩm nổi bật</h2>
    <p>Nơi có nhiều mặc hàng nổi bật được đánh giá cao</p>


    <div class="pro-container">
        @foreach (var item in ViewBag.topSellingProducts)
        {
            SalesOff sales = new SalesOff(item.product_id);
            SalesOffDecorator s = new BlackFridaySalesDecorator(sales);
            double price = (double)item.product_price;

            <div class="pro">
                <a href="@Url.Action("Index","ProductDetail", new { id=item.product_id })">
                    <img src="@item.product_image" alt="">
                    <div class="des">
                        <span>@item.ThuongHieu.brand_name</span>
                        <h5>@item.product_name</h5>
                        <div class="star">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                        </div>
                        @if (s != null)
                        {
                            double priceAfter = s.GetSalesPrice();
                            <h4><span style="color: #ff0000">@priceAfter.ToString("#,##0 VND")</span><s style="color: #808080; margin-left: 14px;">@price.ToString("#,##0 VND")</s></h4>
                        }
                        else
                        {
                            <h4><span style="color: #ff0000">@price.ToString("#,##0 VND")</span></h4>
                        }
                    </div>
                    <a href="@Url.Action("AddToCart", "Cart", new { productId = item.product_id })"><i class="fa-solid fa-cart-shopping cart"></i></a>
                </a>
            </div>
        }
    </div>
</section>

<!-- ... (các phần code khác) ... -->


<section id="banner" class="section-m1">
    <h4>Các dịch vụ sửa chữa</h4>
    <h2>Giảm giá lên đến <span>70%</span> - Tất cả các mặt hàng Vali, Túi xách - Phụ kiện</h2>
    <button class="normal">Khám phá</button>
</section>

<!--New Arrivals-->
<section class="section-p1" id="products1">
    <h2>Sản phẩm mới ra mắt</h2>
    <p>Các sản phẩm, các collection mới được ra mắt</p>
    <div class="pro-container">
        @foreach (var item in ViewBag.newArrival)
        {
            SalesOff sales = new SalesOff(item.product_id);
            SalesOffDecorator s = new BlackFridaySalesDecorator(sales);
            double price = (double)item.product_price;
            <div class="pro">
                <a href="@Url.Action("Index","ProductDetail", new { id=item.product_id })">
                    <img src="@item.product_image" alt="">
                    <div class="des">
                        <span>@item.ThuongHieu.brand_name</span>
                        <h5>@item.product_name</h5>
                        <div class="star">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                        </div>
                        @if (s != null)
                        {
                            double priceAfter = s.GetSalesPrice();
                            <h4><span style="color: #ff0000">@priceAfter.ToString("#,##0 VND")</span><s style="color: #808080; margin-left: 14px;">@price.ToString("#,##0 VND")</s></h4>
                        }
                        else
                        {
                            <h4><span style="color: #ff0000">@price.ToString("#,##0 VND")</span></h4>
                        }
                    </div>
                    <a href="@Url.Action("AddToCart", "Cart", new { productId = item.product_id })"><i class="fa-solid fa-cart-shopping cart"></i></a>
                </a>
            </div>
        }
    </div>
</section>

<section id="sm-banner" class="section-p1">
    <div class="banner-box">
        <h4>Khuyến mãi cực sốc</h4>
        <h2>mua 1 tặng 1</h2>
        <span>Các mẫu Vali cổ điển đang được bày bán tại CaraStore</span>
        <button class="white">Tìm hiểu thêm</button>
    </div>

    <div class="banner-box banner-box2">
        <h4>new brand</h4>
        <h2>new brand is coming</h2>
        <span>CaraStore sẽ nhập về hãng Vali, Túi xách hoàn toàn mới</span>
        <button class="white">Collection</button>
    </div>
</section>

CaraLuggage/Views/Home/Shop.cshtml
@model IEnumerable<CaraLuggage.Models.SanPham>
@{
    ViewBag.Title = "Cửa hàng";
    Layout = "~/Views/Shared/UserView.cshtml";
}
@using CaraLuggage.Controllers.DecoratorPattern;

@{ 
    string sorting = Session["Sorting"] as string;
}

<section id="page-header">
    <h2>#datngaynhanlientay</h2>
    <p>Tiết kiệm với các Voucher và giảm giá lên đến 70%</p>
</section>

<section class="section-p1" id="products1">
    <div class="pro-container" style="justify-content: flex-start;">
        <div class="dropdown">
            <button class="dropbtn"><i class="fa-solid fa-filter" id="filter"></i> Lọc</button>
            <div class="dropdown-content">
                <a href="@Url.Action("PriceSortingHighToLow", new { page = ViewBag.PageNumber })">Giá từ cao đến thấp</a>
                <a href="@Url.Action("PriceSortingLowToHigh")">Giá từ thấp đến cao</a>
                <a href="@Url.Action("AlphabetSortingAToZ")">Theo thứ tự từ a - z</a>
                <a href="@Url.Action("AlphabetSortingZToA")">Theo thứ tự từ z - a</a>
            </div>
        </div>
    </div>
    <div class="pro-container">
        @foreach (var item in Model)
        {
            SalesOff sales = new SalesOff(item.product_id);
            SalesOffDecorator s = new BlackFridaySalesDecorator(sales);
            double price = (double)item.product_price;

            <div class="pro">
                <a href="@Url.Action("Index","ProductDetail", new { id=item.product_id })">
                    <img src="@item.product_image" alt="">
                    <div class="des">
                        <span>@item.ThuongHieu.brand_name</span>
                        <h5>@item.product_name</h5>
                        <div class="star">
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                            <i class="fas fa-star"></i>
                        </div>
                        @if (s != null)
                        {
                            double priceAfter = s.GetSalesPrice();
                            <h4><span style="color: #ff0000">@priceAfter.ToString("#,##0 VND")</span><s style="color: #808080; margin-left: 14px;">@price.ToString("#,##0 VND")</s></h4>
                        }
                        else
                        {
                            <h4><span style="color: #ff0000">@price.ToString("#,##0 VND")</span></h4>
                        }
                    </div>
                    <a href="@Url.Action("AddToCart", "Cart", new { productId = item.product_id })"><i class="fa-solid fa-cart-shopping cart"></i></a>
                </a>
            </div>
        }
    </div>
</section>

<section id="pagination">
    @for (int i = 1; i <= ViewBag.TotalPages; i++)
    {
        if (sorting == "A to Z")
        {
            <a href="@Url.Action("AlphabetSortingAToZ", new { page = i })">@i</a>
        }
        else if (sorting == "Z to A")
        {
            <a href="@Url.Action("AlphabetSortingZToA", new { page = i })">@i</a>
        }
        else if (sorting == "High to Low")
        {
            <a href="@Url.Action("PriceSortingHighToLow", new { page = i })">@i</a>
        }
        else if (sorting == "Low to High")
        {
            <a href="@Url.Action("PriceSortingLowToHigh", new { page = i })">@i</a>
        }
        else
        {
            <a href="@Url.Action("Shop", new { page = i })">@i</a>
        }
    }
</section>

CaraLuggage/Views/Home/UserOrder.cshtml
@model IEnumerable<CaraLuggage.Models.DonHang>
@{
    ViewBag.Title = "Danh sách đơn (Khách hàng)";
    Layout = "~/Views/Shared/UserView.cshtml";
}

@{
    string sessionCus = Session["CusID"] as string;
}

<section id="page-header" class="about-header10">
    <h2>#thongtincuaban</h2>
    <p>Nơi bạn có thể tra cứu thông tin của mình!</p>
</section>

<section id="profile" class="section-p1">
    <div class="profile-info">
        <h3>Thông tin tài khoản</h3>
        <ul class="pro-info">
            <li><a href="@Url.Action("UserProfile", "Home", new { cusID = sessionCus })">Thông tin cá nhân</a></li>
            <li><a class="active1" href="@Url.Action("UserOrder", new {  cusID = sessionCus  })">Đơn hàng</a></li>
            <li><a href="@Url.Action("Logout", "LoginRegister")">Đăng xuất</a></li>
        </ul>
    </div>

    <div class="profile-details">
        <h3>Đơn hàng</h3>
        <table class="table">
            <thead>
                <tr class="border">
                    <th class="first">Mã Đơn</th>
                    <th>Ngày Lập</th>
                    <th>Trạng Thái</th>
                    <th>Thanh Toán</th>
                    <th>Giao Hàng</th>
                    <th>Hành Động</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="border">
                        <th class="first">
                            @Html.DisplayFor(modelItem => item.order_code)
                        </th>
                        <td>
                            @Html.DisplayFor(modelItem => item.order_createAt)
                        </td>
                        <td>
                            <span>
                                @Html.DisplayFor(modelItem => item.order_status)
                            </span>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PhuongThucThanhToan.payment_name)
                        </td>
                        <td>
                            <span>Chờ đóng gói</span>
                        </td>
                        <td>
                            <div class="normal">
                                <a href="@Url.Action("UserOrderDetail","Home", new { id=item.order_no})">Xem</a>
                            </div>
                        </td>
                    </tr>
                }
                </tbody>
        </table>
    </div>
</section>

CaraLuggage/Views/Home/UserProfile.cshtml
@model CaraLuggage.Models.KhachHang

@{
    ViewBag.Title = "Thông tin khách hàng";
    Layout = "~/Views/Shared/UserView.cshtml";
}

@{ 
    bool isLoginFB_GG = false; // Khởi tạo giá trị mặc định
    if (Session["LoginFB_GG"] != null)
    {
        isLoginFB_GG = (bool)Session["LoginFB_GG"]; // Ép kiểu dữ liệu
    }
}

<section id="page-header" class="about-header10">
    <h2>#thongtincuaban</h2>
    <p>Nơi bạn có thể tra cứu thông tin của mình!</p>
</section>

<section id="profile" class="section-p1">
    <div class="profile-info">
        <h3>Thông tin tài khoản</h3>
        <ul class="pro-info">
            <li><a class="active1" href="@Url.Action("UserProfile", "Home", new { cusID = Model.customer_id })">Thông tin cá nhân</a></li>
            <li><a href="@Url.Action("UserOrder", "Home", new {  cusID = Model.customer_id  })">Đơn hàng</a></li>
            <li><a href="@Url.Action("Logout", "LoginRegister")">Đăng xuất</a></li>
        </ul>
    </div>

    <div class="profile-details">
        <div id="pro-edit">
            @using (Html.BeginForm("Edit", "Customers", new { id = Model.customer_id }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.customer_id)
                @Html.HiddenFor(model => model.customer_account)

                <h3>Thông tin cá nhân</h3>

                <h5>Sửa thông tin</h5>
                <div class="tenvasdt">
                    <div class="hovaten-pro">
                        <label for="">Họ và tên</label>
                        @Html.EditorFor(model => model.customer_name)
                    </div>
                    <div class="sodienthoai-pro">
                        <label for="">Số điện thoại</label>
                        @Html.EditorFor(model => model.customer_phone, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="diachi-pro">
                    <label for="">Địa chỉ</label>
                    @Html.EditorFor(model => model.customer_address, new { htmlAttributes = new { @class = "form-control" } })
                </div>

                if (isLoginFB_GG == true)
                {
                    <div class="diachi-pro">
                        <label for="">Email</label>
                        @Html.EditorFor(model => model.TaiKhoan.account_name, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                    </div>
                }
                <button class="normal" type="submit">Lưu thay đổi</button>
            }
        </div>
        @if (isLoginFB_GG == false)
        {
            using (Html.BeginForm("Edit", "Accounts", new { id = Model.customer_id }, FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                <div>
                    <h3>Đổi mật khẩu</h3>
                    <div class="pass-pro">
                        <label for="">Tên đăng nhập</label>
                        @Html.EditorFor(model => model.TaiKhoan.account_name, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    <div class="pass-pro" id="pro-pass">
                        <label for="">Mật khẩu</label>
                        @Html.EditorFor(model => model.TaiKhoan.account_password, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                    </div>
                    <div class="pass-pro" id="pro-pass">
                        <label for="">Mật khẩu mới</label>
                        @Html.EditorFor(model => model.TaiKhoan.account_password, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                    <button class="normal" type="submit">Lưu thay đổi</button>
                </div>
            }
        }

    </div>
</section>