CaraLuggage/Controllers/AdminController/MaterialsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CaraLuggage.Models;

namespace CaraLuggage.Controllers.AdminController
{
    public class MaterialsController : Controller
    {
        private CaraLuggageDBEntities db = new CaraLuggageDBEntities();

        // GET: Materials
        public ActionResult Index()
        {
            return View(db.ChatLieux.ToList());
        }

        // GET: Materials/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChatLieu chatLieu = db.ChatLieux.Find(id);
            if (chatLieu == null)
            {
                return HttpNotFound();
            }
            return View(chatLieu);
        }

        // GET: Materials/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Materials/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "material_id,material_name")] ChatLieu chatLieu)
        {
            if (ModelState.IsValid)
            {
                db.ChatLieux.Add(chatLieu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(chatLieu);
        }

        // GET: Materials/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChatLieu chatLieu = db.ChatLieux.Find(id);
            if (chatLieu == null)
            {
                return HttpNotFound();
            }
            return View(chatLieu);
        }

        // POST: Materials/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "material_id,material_name")] ChatLieu chatLieu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(chatLieu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(chatLieu);
        }

        // GET: Materials/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ChatLieu chatLieu = db.ChatLieux.Find(id);
            if (chatLieu == null)
            {
                return HttpNotFound();
            }
            return View(chatLieu);
        }

        // POST: Materials/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ChatLieu chatLieu = db.ChatLieux.Find(id);
            db.ChatLieux.Remove(chatLieu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CaraLuggage/Views/Materials/Create.cshtml
@model CaraLuggage.Models.ChatLieu

@{
    ViewBag.Title = "Quản lý chất liệu (Admin)";
    Layout = "~/Views/Shared/AdminView.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Thêm mới chất liệu</h4>
                </div>

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="card-body">
                    <form>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.material_name)
                                    @Html.EditorFor(model => model.material_name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.material_name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-success btn-fill pull-right">Tạo mới</button>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

CaraLuggage/Views/Materials/Delete.cshtml
@model CaraLuggage.Models.ChatLieu

@{
    ViewBag.Title = "Quản lý chất liệu (Admin)";
    Layout = "~/Views/Shared/AdminView.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Xóa loại chất liệu?</h4>
                </div>

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.material_id)
                <div class="card-body">
                    <form>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.material_name)
                                    @Html.EditorFor(model => model.material_name, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                    @Html.ValidationMessageFor(model => model.material_name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-danger btn-fill pull-right">Xóa</button>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

CaraLuggage/Views/Materials/Edit.cshtml
@model CaraLuggage.Models.ChatLieu

@{
    ViewBag.Title = "Quản lý chất liệu (Admin)";
    Layout = "~/Views/Shared/AdminView.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Chỉnh sửa chất liệu</h4>
                </div>

                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @Html.HiddenFor(model => model.material_id)
                <div class="card-body">
                    <form>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    @Html.LabelFor(model => model.material_name)
                                    @Html.EditorFor(model => model.material_name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.material_name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-info btn-fill pull-right">Lưu</button>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
}

CaraLuggage/Views/Materials/Index.cshtml
@model IEnumerable<CaraLuggage.Models.ChatLieu>

@{
    ViewBag.Title = "Quản lý chất liệu (Admin)";
    Layout = "~/Views/Shared/AdminView.cshtml";
}
<style>
    .crud-btn {
        display: inline-block;
        width: 40px;
        height: 40px;
        border-radius: 100%;
        margin: 2px;
    }

        .crud-btn i {
            display: flex;
            justify-content: center;
            align-items: center;
            width: 100%;
            height: 100%;
        }

</style>


<div class="row">
    <div class="col-md-12">
        <div class="card strpied-tabled-with-hover">
            <div class="card-header ">
                <h4 class="card-title">Bảng Quản lý Chất liệu</h4>
                @*<p class="card-category">Here is a subtitle for this table</p>*@
            </div>
            <div class="card-body table-responsive">
                <table class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.material_id)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.material_name)
                            </th>
                            <th>Action</th>
                        </tr>

                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.material_id)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.material_name)
                                </td>
                                <td style="height: 100%; align-items: center;">
                                    <a href="@Url.Action("Edit", new { id=item.material_id })" class="crud-btn btn-info">
                                        <i class="fa-solid fa-pen-to-square"></i>
                                    </a>
                                    <a href="@Url.Action("Delete", new { id=item.material_id })" class="crud-btn btn-danger">
                                        <i class="fa-solid fa-x">
                                        </i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <div class="card-footer clearfix">
                <a href="@Url.Action("Create", "Materials")" class="btn btn-success float-left">Thêm màu sắc mới</a>
            </div>
        </div>
    </div>
</div>